name: Gestao de Vagas Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar projeto
        run: ./mvnw clean package